using DataToolkit.Builder.Configuration;
using Microsoft.Extensions.Options;

namespace DataToolkit.Builder.Services;

public sealed class MigrationDdlGeneratorService
{
    private readonly MigrationOptions _options;

    public MigrationDdlGeneratorService(
        IOptions<MigrationOptions> options)
    {
        _options = options.Value;
    }

    public async Task GenerateDdlScriptsAsync(
        List<TableMetadata> metadata)
    {
        Directory.CreateDirectory(
            _options.SqlOutputPath);

        foreach (var table in metadata)
        {
            var ddl =
                BuildCreateTable(table);

            var fileName =
                $"DDL_{table.Schema}.WF_{table.Name}.sql";

            var filePath =
                Path.Combine(
                    _options.SqlOutputPath,
                    fileName);

            await File.WriteAllTextAsync(
                filePath,
                ddl);
        }
    }

    private static string BuildCreateTable(
        TableMetadata table)
    {
        var columns =
            string.Join(
                "," + Environment.NewLine,
                table.Columns.Select(BuildColumn));

        return
$"""
/*
====================================================
TABLE : WF_{table.Name}
GENERATED BY DataToolkit.Builder
====================================================
*/

IF OBJECT_ID('{table.Schema}.WF_{table.Name}') IS NULL
BEGIN

    CREATE TABLE [{table.Schema}].[WF_{table.Name}]
    (
{columns}
    );

END
GO
""";
    }

    private static string BuildColumn(
        ColumnMetadata column)
    {
        return
            $"        [{column.Name}] {BuildSqlType(column)} NULL";
    }

    private static string BuildSqlType(
        ColumnMetadata column)
    {
        var type =
            column.SqlType;
        
        if (!string.IsNullOrWhiteSpace(column.MaxLength))
        {
            return $"{type}({column.MaxLength})";
        }

        if (Convert.ToInt32(column.MaxLength) > 0)
        {
            return $"{type}({column.MaxLength})";
        }

            return type;
    }
}