using DataToolkit.MigrationBuilder.Configuration;
using DataToolkit.MigrationBuilder.Helpers;
using DataToolkit.MigrationBuilder.Models.Metadata;
using Microsoft.Extensions.Options;

namespace DataToolkit.MigrationBuilder.Services.Migration;

/// <summary>
/// Generates SQL extraction artifacts.
/// WorkFile -> SELECT.
/// Staging -> INSERT.
/// </summary>
public sealed class MigrationExtractionGeneratorService
{
    private readonly MigrationOptions _options;

    public MigrationExtractionGeneratorService(IOptions<MigrationOptions> options)
    {
        _options = options.Value;
    }

    public async Task GenerateExtractionScriptsAsync(
        List<TableMetadata> metadataSource,
        List<TableMetadata> metadataTarget,
        ArtifactType artifactType)
    {
        Directory.CreateDirectory(_options.SqlOutputPath);

        foreach (TableMetadata sourceTable in metadataSource)
        {
            TableMetadata? targetTable = metadataTarget.FirstOrDefault(t =>
                t.Schema.Equals(sourceTable.Schema, StringComparison.OrdinalIgnoreCase) &&
                t.Name.Equals(sourceTable.Name, StringComparison.OrdinalIgnoreCase));

            if (targetTable is null)
                continue;

            string sql = BuildExtractionScript(sourceTable, targetTable, artifactType);

            string prefix = artifactType == ArtifactType.WorkFile ? "WF" : "STG";

            string fileName = $"SQL_{sourceTable.Schema}.{prefix}_{sourceTable.Name}.sql";

            await File.WriteAllTextAsync(
                Path.Combine(_options.SqlOutputPath, fileName),
                sql);
        }
    }

    private static string BuildExtractionScript(
        TableMetadata sourceTable,
        TableMetadata targetTable,
        ArtifactType artifactType)
    {
        return artifactType switch
        {
            ArtifactType.WorkFile => BuildSelect(sourceTable, targetTable),
            ArtifactType.Staging => BuildInsertScript(sourceTable),
            _ => throw new NotSupportedException()
        };
    }

    private static string BuildSelect(
        TableMetadata sourceTable,
        TableMetadata targetTable)
    {
        List<string> selectColumns = [];

        foreach (ColumnMetadata targetColumn in targetTable.Columns)
        {
            ColumnMetadata? sourceColumn = sourceTable.Columns.FirstOrDefault(c =>
                c.Name.Equals(targetColumn.Name, StringComparison.OrdinalIgnoreCase));

            selectColumns.Add(sourceColumn is not null
                ? $"    [{sourceColumn.Name}]"
                : $"    NULL AS [{targetColumn.Name}]");
        }

        string select = string.Join("," + Environment.NewLine, selectColumns);

        return $"""
/*
====================================================
TABLE : WF_{sourceTable.Name}
GENERATED BY DataToolkit.MigrationBuilder
====================================================
*/

SELECT
{select}
FROM [{sourceTable.Schema}].[{sourceTable.Name}];
""";
    }

    private static string BuildInsertScript(TableMetadata sourceTable)
    {
        return $"""
/*
====================================================
TABLE : STG_{sourceTable.Name}
GENERATED BY DataToolkit.MigrationBuilder
====================================================
*/

-- TODO:
-- Generate INSERT statements.
""";
    }
}
