using DataToolkit.MigrationBuilder.Configuration;
using DataToolkit.MigrationBuilder.Helpers;
using DataToolkit.MigrationBuilder.Models.Metadata;
using Microsoft.Extensions.Options;

namespace DataToolkit.MigrationBuilder.Services.Migration;

public sealed class MigrationDdlGeneratorService
{
    private readonly MigrationOptions _options;

    public MigrationDdlGeneratorService(
        IOptions<MigrationOptions> options)
    {
        _options = options.Value;
    }

    public async Task GenerateDdlScriptsAsync(
        List<TableMetadata> metadataSource,
        List<TableMetadata> metadataTarget,
        ArtifactType artifactType)
    {
        Directory.CreateDirectory(
            _options.SqlOutputPath);

        foreach (TableMetadata sourceTable in metadataSource)
        {
            TableMetadata? targetTable =
                metadataTarget.FirstOrDefault(t =>
                    t.Schema.Equals(
                        sourceTable.Schema,
                        StringComparison.OrdinalIgnoreCase)
                    &&
                    t.Name.Equals(
                        sourceTable.Name,
                        StringComparison.OrdinalIgnoreCase));

            if (targetTable is null)
                continue;

            string ddl = BuildCreateTable(sourceTable, targetTable, artifactType);

            string artifactName =
                artifactType == ArtifactType.WorkFile
                    ? "WF"
                    : "STG";

            string fileName =
                $"DDL_{sourceTable.Schema}.{artifactName}_{sourceTable.Name}.sql";

            string filePath =
                Path.Combine(
                    _options.SqlOutputPath,
                    fileName);

            await File.WriteAllTextAsync(
                filePath,
                ddl);
        }
    }

    private static string BuildCreateTable(
        TableMetadata sourceTable,
        TableMetadata targetTable,
        ArtifactType artifactType)
    {
        string artifactPrefix =
            artifactType == ArtifactType.WorkFile
                ? "WF"
                : "STG";

        List<string> columns = [];

        // El WFile/Homologation utiliza siempre la estructura del destino para garantizar compatibilidad con la carga.
        foreach (ColumnMetadata targetColumn in targetTable.Columns)
        {
            columns.Add(
                BuildColumn(targetColumn));
        }

        string columnScript =
            string.Join(
                "," + Environment.NewLine,
                columns);

        return
$"""
/*
====================================================
TABLE : {artifactPrefix}_{sourceTable.Name}
GENERATED BY DataToolkit.MigrationBuilder
- No constraints, No identities, All columns nullable.
====================================================
*/

IF OBJECT_ID('{sourceTable.Schema}.{artifactPrefix}_{sourceTable.Name}') IS NOT NULL
BEGIN
    DROP TABLE [{sourceTable.Schema}].[{artifactPrefix}_{sourceTable.Name}];
END
GO
CREATE TABLE [{sourceTable.Schema}].[{artifactPrefix}_{sourceTable.Name}]
(
{columnScript}
);
GO
""";
    }

    private static string BuildColumn(
        ColumnMetadata column)
    {
        return
            $"        [{column.Name}] {BuildSqlType(column)} NULL";
    }

    private static string BuildSqlType(ColumnMetadata column)
    {
        var type = column.SqlType.ToLowerInvariant();

        return type switch
        {
            "char" or "varchar" or "nchar" or "nvarchar"
            or "binary" or "varbinary"
                => string.IsNullOrWhiteSpace(column.MaxLength)
                    ? column.SqlType
                    : $"{column.SqlType}({column.MaxLength})",

            "decimal" or "numeric"
                => string.IsNullOrWhiteSpace(column.Precision) ||
                   string.IsNullOrWhiteSpace(column.Scale)
                    ? column.SqlType
                    : $"{column.SqlType}({column.Precision},{column.Scale})",

            "datetime2" or "datetimeoffset" or "time"
                => string.IsNullOrWhiteSpace(column.Scale)
                    ? column.SqlType
                    : $"{column.SqlType}({column.Scale})",

            _ => column.SqlType
        };
    }


}