using DataToolkit.MigrationBuilder.Configuration;
using DataToolkit.MigrationBuilder.Helpers;
using DataToolkit.MigrationBuilder.Models.Metadata;
using Microsoft.Extensions.Options;

namespace DataToolkit.MigrationBuilder.Services.Migration;

public sealed class MigrationDdlGeneratorService
{
    private readonly MigrationOptions _options;

    public MigrationDdlGeneratorService(
        IOptions<MigrationOptions> options)
    {
        _options = options.Value;
    }

    public async Task GenerateDdlScriptsAsync(
        List<TableMetadata> metadataSource,
        List<TableMetadata> metadataTarget,
        ArtifactType artifactType)
    {
        Directory.CreateDirectory(
            _options.SqlOutputPath);

        foreach (TableMetadata sourceTable in metadataSource)
        {
            TableMetadata? targetTable =
                metadataTarget.FirstOrDefault(t =>
                    t.Schema.Equals(
                        sourceTable.Schema,
                        StringComparison.OrdinalIgnoreCase)
                    &&
                    t.Name.Equals(
                        sourceTable.Name,
                        StringComparison.OrdinalIgnoreCase));

            if (targetTable is null)
                continue;

            string ddl =
                BuildCreateTable(
                    sourceTable,
                    targetTable,
                    artifactType);

            string artifactName =
                artifactType == ArtifactType.WorkFile
                    ? "WF"
                    : "HM";

            string fileName =
                $"DDL_{sourceTable.Schema}.{artifactName}_{sourceTable.Name}.sql";

            string filePath =
                Path.Combine(
                    _options.SqlOutputPath,
                    fileName);

            await File.WriteAllTextAsync(
                filePath,
                ddl);
        }
    }

    private static string BuildCreateTable(
        TableMetadata sourceTable,
        TableMetadata targetTable,
        ArtifactType artifactType)
    {
        string artifactPrefix =
            artifactType == ArtifactType.WorkFile
                ? "WF"
                : "HM";

        List<string> columns = [];

        //
        // Todas las columnas del origen
        //

        foreach (ColumnMetadata sourceColumn in sourceTable.Columns)
        {
            columns.Add(
                BuildColumn(sourceColumn));
        }

        //
        // Columnas que solo existen en destino
        //

        foreach (ColumnMetadata targetColumn in targetTable.Columns)
        {
            bool existsInSource =
                sourceTable.Columns.Any(c =>
                    c.Name.Equals(
                        targetColumn.Name,
                        StringComparison.OrdinalIgnoreCase));

            if (existsInSource)
                continue;

            columns.Add(
                BuildColumn(targetColumn));
        }

        string columnScript =
            string.Join(
                "," + Environment.NewLine,
                columns);

        return
$"""
/*
====================================================
TABLE : {artifactPrefix}_{sourceTable.Name}
GENERATED BY DataToolkit.MigrationBuilder
====================================================
*/

IF OBJECT_ID('{sourceTable.Schema}.{artifactPrefix}_{sourceTable.Name}') IS NULL
BEGIN

    CREATE TABLE [{sourceTable.Schema}].[{artifactPrefix}_{sourceTable.Name}]
    (
{columnScript}
    );

END
GO
""";
    }

    private static string BuildColumn(
        ColumnMetadata column)
    {
        return
            $"        [{column.Name}] {BuildSqlType(column)} NULL";
    }

    private static string BuildSqlType(
        ColumnMetadata column)
    {
        string type =
            column.SqlType;

        if (string.IsNullOrWhiteSpace(column.MaxLength))
        {
            return type;
        }

        return $"{type}({column.MaxLength})";
    }
}